---
title: "wordle"
author: "Jyhreh Johnson"
date: "2/10/2022"
output: html_document
---

Step 1
```{r}
load_dictionary <- function(filename){
        x <- read.delim(filename)
        return(x$words)
}
```

```{r}
valid_list <- load_dictionary("collins-scrabble-words-2019.txt")

solution_list <-load_dictionary("google-10000-english-usa-no-swears.txt")
```

Step 2
```{r}
solution_list <- intersect(valid_list, solution_list)
```
How many words are in your updated solution_list vector?
-There are 8,336 word entries.

Step 3
```{r}
pick_solution <- function(solution_list, word_length = 5){
        s_length <- as.data.frame(solution_list)
        names(s_length) <- c("word")
        s_length <- dplyr::filter(s_length,nchar(word) == word_length)
        word <- dplyr:: sample_n(s_length, size = 1)
        word <- word$word %>%
          strsplit(word, split = "")
        word <- word[[1]]
        return(word)
}
      
solution <- pick_solution(solution_list, word_length = 5)
```

Step 4
```{r}
evaluate_guess <- function(guess, solution){
        library(sjmisc)
        word_length <- length(solution)
        text_feedback <- rep("-", word_length)
        for( i in 1: word_length){
          text_feedback [i] <- case_when(
            guess[i] == solution[i] ~ "*",
            guess[i] %in% solution & guess[i] != solution[i] ~ "+",
            guess[i] %nin% solution ~ "-"
          )
    }
    return(text_feedback)
}
          
play_wordle <- function(solution, valid_list,num_guesses = 6){
      library(tidyverse)
      library(sjmisc)
      word_length <- length(solution)
      print("Hello! Welcome to R-Wordle. In this game, you will have 6 chances to guess the hidden 5 letter word. Good luck!")
      print("Available Letters:")
      letters_left <- LETTERS
      print(letters_left)
      
      guess_history <- data.frame(matrix(nrow = word_length, ncol= num_guesses))
      feedback_history <- data.frame(matrix(nrow = word_length, ncol= num_guesses))
      
      for(i in 1:num_guesses){
        guess <- readline("Please input your word guess, then press return/enter to submit your guess: ")%>%
          toupper()
        while(nchar(guess) > word_length | toupper(guess) %nin% valid_list){
          print("Oh no! :/ Your guess is incorrect, please input another guess.")
            guess <- readline("Please input another guess: ")%>%
              toupper()
          }
        guess <- strsplit(guess, split = "")[[1]]
        print(guess) 
        guess_history[,i] <- guess
        feedback <- evaluate_guess(guess,solution)
        feedback_history[,i] <- feedback
        print("Available Letters:")
        letters_left <- setdiff(letters_left, guess)
        print(letters_left)
        print(feedback)
        
        if(setequal(feedback, rep("*", word_length))){
          print("Congratulations! You won the Wordle!")
          print(guess_history)
          return(feedback_history)
        }
      }
      
      print("Sorry! :/ Your guesses were incorrect, you have run out of chances.")
      print(feedback_history)
      print(guess_history)
}
       play_wordle(solution, valid_list, num_guesses = 6)
```